"""First-deploy seed data for MarketDeck.

The server imports these constants during startup when it initializes an empty
PostgreSQL database.
"""

SEED_SETTINGS = {
    "GLOBAL_BASE_CURRENCY": "EUR",
}

SEED_WATCHLISTS = [{'slug': 'us-sectors',
  'name': 'US GICS Sector ETFs',
  'short_name': 'US Sectors',
  'category': 'ETFs',
  'description': 'Rank all 11 S&P 500 ETFs by momentum. Hold the top N equally weighted. Rebalance monthly. Returns '
                 "calculated from today's price vs. the closing price exactly N months ago.",
  'tag': 'SPDR ETFs · LIVE DATA',
  'currency': 'USD',
  'show_tag': True},
 {'slug': 'eu-sectors',
  'name': 'EU ICB Supersectors ETFs',
  'short_name': 'EU Supersectors',
  'category': 'ETFs',
  'description': 'Rank European STOXX 600 ETFs (iShares, Xetra-listed) by momentum. Hold the top N equally weighted. '
                 'Rebalance monthly.',
  'tag': 'iShares STOXX 600 · LIVE DATA',
  'currency': 'EUR',
  'show_tag': True},
 {'slug': 'country-etfs',
  'name': 'iShares Country ETFs',
  'short_name': 'Countries',
  'category': 'ETFs',
  'description': 'Rank iShares MSCI Country ETFs by momentum. Hold the top N equally weighted. Rebalance monthly.',
  'tag': 'iShares MSCI · LIVE DATA',
  'currency': 'USD',
  'show_tag': True},
 {'slug': 'commodities',
  'name': 'Commodities ETFs & Funds',
  'short_name': 'Commodities',
  'category': 'Futures',
  'description': 'Rank various commodity ETFs and ETCs by momentum. Hold the top N equally weighted. Rebalance '
                 'monthly.',
  'tag': 'Broad Commodities · LIVE DATA',
  'currency': 'USD',
  'show_tag': True},
 {'slug': 'global-99',
  'name': 'Top 99 Global Equities',
  'short_name': 'Global 99',
  'category': 'Stocks',
  'description': 'Rank the top 99 global stocks by market cap. Hold the top N equally weighted. Rebalance monthly.',
  'tag': 'Global Equities · LIVE DATA',
  'currency': 'USD',
  'show_tag': True}]

SEED_TICKERS = [{'watchlist_slug': 'us-sectors',
  'symbol': 'XLY',
  'name': 'Consumer Discretionary',
  'tag': 'Cyclical',
  'currency': 'USD'},
 {'watchlist_slug': 'us-sectors', 'symbol': 'XLP', 'name': 'Consumer Staples', 'tag': 'Defensive', 'currency': 'USD'},
 {'watchlist_slug': 'us-sectors', 'symbol': 'XLE', 'name': 'Energy', 'tag': 'Cyclical', 'currency': 'USD'},
 {'watchlist_slug': 'us-sectors', 'symbol': 'XLF', 'name': 'Financials', 'tag': 'Cyclical', 'currency': 'USD'},
 {'watchlist_slug': 'us-sectors', 'symbol': 'XLV', 'name': 'Health Care', 'tag': 'Defensive', 'currency': 'USD'},
 {'watchlist_slug': 'us-sectors', 'symbol': 'XLI', 'name': 'Industrials', 'tag': 'Cyclical', 'currency': 'USD'},
 {'watchlist_slug': 'us-sectors', 'symbol': 'XLB', 'name': 'Materials', 'tag': 'Cyclical', 'currency': 'USD'},
 {'watchlist_slug': 'us-sectors', 'symbol': 'XLK', 'name': 'Technology', 'tag': 'Cyclical', 'currency': 'USD'},
 {'watchlist_slug': 'us-sectors', 'symbol': 'XLU', 'name': 'Utilities', 'tag': 'Defensive', 'currency': 'USD'},
 {'watchlist_slug': 'us-sectors', 'symbol': 'XLRE', 'name': 'Real Estate', 'tag': 'Defensive', 'currency': 'USD'},
 {'watchlist_slug': 'us-sectors',
  'symbol': 'XLC',
  'name': 'Communication Services',
  'tag': 'Cyclical',
  'currency': 'USD'},
 {'watchlist_slug': 'eu-sectors', 'symbol': 'EXV3.DE', 'name': 'Technology', 'tag': 'Cyclical', 'currency': 'EUR'},
 {'watchlist_slug': 'eu-sectors',
  'symbol': 'EXV2.DE',
  'name': 'Telecommunications',
  'tag': 'Defensive',
  'currency': 'EUR'},
 {'watchlist_slug': 'eu-sectors',
  'symbol': 'EXV5.DE',
  'name': 'Automobiles & Parts',
  'tag': 'Cyclical',
  'currency': 'EUR'},
 {'watchlist_slug': 'eu-sectors', 'symbol': 'EXV1.DE', 'name': 'Banks', 'tag': 'Cyclical', 'currency': 'EUR'},
 {'watchlist_slug': 'eu-sectors',
  'symbol': 'EXH2.DE',
  'name': 'Financial Services',
  'tag': 'Cyclical',
  'currency': 'EUR'},
 {'watchlist_slug': 'eu-sectors', 'symbol': 'EXV4.DE', 'name': 'Health Care', 'tag': 'Defensive', 'currency': 'EUR'},
 {'watchlist_slug': 'eu-sectors', 'symbol': 'EXI5.DE', 'name': 'Real Estate', 'tag': 'Defensive', 'currency': 'EUR'},
 {'watchlist_slug': 'eu-sectors', 'symbol': 'EXV6.DE', 'name': 'Basic Resources', 'tag': 'Cyclical', 'currency': 'EUR'},
 {'watchlist_slug': 'eu-sectors',
  'symbol': 'EXH3.DE',
  'name': 'Food & Beverage',
  'tag': 'Defensive',
  'currency': 'EUR'},
 {'watchlist_slug': 'eu-sectors',
  'symbol': 'EXV9.DE',
  'name': 'Travel & Leisure',
  'tag': 'Cyclical',
  'currency': 'EUR'},
 {'watchlist_slug': 'eu-sectors',
  'symbol': 'EXV8.DE',
  'name': 'Construction & Materials',
  'tag': 'Cyclical',
  'currency': 'EUR'},
 {'watchlist_slug': 'eu-sectors', 'symbol': 'EXV7.DE', 'name': 'Chemicals', 'tag': 'Cyclical', 'currency': 'EUR'},
 {'watchlist_slug': 'eu-sectors',
  'symbol': 'EXH4.DE',
  'name': 'Industrial Goods & Svcs',
  'tag': 'Cyclical',
  'currency': 'EUR'},
 {'watchlist_slug': 'eu-sectors',
  'symbol': 'EXH7.DE',
  'name': 'Personal & Household Goods',
  'tag': 'Defensive',
  'currency': 'EUR'},
 {'watchlist_slug': 'eu-sectors', 'symbol': 'EXH6.DE', 'name': 'Media', 'tag': 'Cyclical', 'currency': 'EUR'},
 {'watchlist_slug': 'eu-sectors', 'symbol': 'EXH5.DE', 'name': 'Insurance', 'tag': 'Defensive', 'currency': 'EUR'},
 {'watchlist_slug': 'eu-sectors', 'symbol': 'EXH9.DE', 'name': 'Utilities', 'tag': 'Defensive', 'currency': 'EUR'},
 {'watchlist_slug': 'eu-sectors', 'symbol': 'EXH8.DE', 'name': 'Retail', 'tag': 'Cyclical', 'currency': 'EUR'},
 {'watchlist_slug': 'eu-sectors', 'symbol': 'EXH1.DE', 'name': 'Oil & Gas', 'tag': 'Cyclical', 'currency': 'EUR'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EWA', 'name': 'Australia', 'tag': 'Oceania', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EWO', 'name': 'Austria', 'tag': 'Europe', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EWK', 'name': 'Belgium', 'tag': 'Europe', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EWZ', 'name': 'Brazil', 'tag': 'Latin America', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EWC', 'name': 'Canada', 'tag': 'North America', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'MCHI', 'name': 'China', 'tag': 'Asia', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EWQ', 'name': 'France', 'tag': 'Europe', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EWG', 'name': 'Germany', 'tag': 'Europe', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EWH', 'name': 'Hong Kong', 'tag': 'Asia', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'INDA', 'name': 'India', 'tag': 'Asia', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EIDO', 'name': 'Indonesia', 'tag': 'Asia', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EIS', 'name': 'Israel', 'tag': 'Middle East', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EWI', 'name': 'Italy', 'tag': 'Europe', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EWJ', 'name': 'Japan', 'tag': 'Asia', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EWM', 'name': 'Malaysia', 'tag': 'Asia', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EWW', 'name': 'Mexico', 'tag': 'Latin America', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EWN', 'name': 'Netherlands', 'tag': 'Europe', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'ENZL', 'name': 'New Zealand', 'tag': 'Oceania', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'ENOR', 'name': 'Norway', 'tag': 'Europe', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EPU', 'name': 'Peru', 'tag': 'Latin America', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EPHE', 'name': 'Philippines', 'tag': 'Asia', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EPOL', 'name': 'Poland', 'tag': 'Europe', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'QAT', 'name': 'Qatar', 'tag': 'Middle East', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'KSA', 'name': 'Saudi Arabia', 'tag': 'Middle East', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EWS', 'name': 'Singapore', 'tag': 'Asia', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EZA', 'name': 'South Africa', 'tag': 'Africa', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EWY', 'name': 'South Korea', 'tag': 'Asia', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EWP', 'name': 'Spain', 'tag': 'Europe', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EWD', 'name': 'Sweden', 'tag': 'Europe', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EWL', 'name': 'Switzerland', 'tag': 'Europe', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EWT', 'name': 'Taiwan', 'tag': 'Asia', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'THD', 'name': 'Thailand', 'tag': 'Asia', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'TUR', 'name': 'Turkey', 'tag': 'Europe', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'UAE', 'name': 'UAE', 'tag': 'Middle East', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs', 'symbol': 'EWU', 'name': 'United Kingdom', 'tag': 'Europe', 'currency': 'USD'},
 {'watchlist_slug': 'country-etfs',
  'symbol': 'EUSA',
  'name': 'United States',
  'tag': 'North America',
  'currency': 'USD'},
 {'watchlist_slug': 'commodities', 'symbol': 'GC=F', 'name': 'Gold', 'tag': 'Metals', 'currency': 'USD'},
 {'watchlist_slug': 'commodities', 'symbol': 'SI=F', 'name': 'Silver', 'tag': 'Metals', 'currency': 'USD'},
 {'watchlist_slug': 'commodities', 'symbol': 'PL=F', 'name': 'Platinum', 'tag': 'Metals', 'currency': 'USD'},
 {'watchlist_slug': 'commodities', 'symbol': 'HG=F', 'name': 'Copper', 'tag': 'Metals', 'currency': 'USD'},
 {'watchlist_slug': 'commodities', 'symbol': 'PA=F', 'name': 'Palladium', 'tag': 'Metals', 'currency': 'USD'},
 {'watchlist_slug': 'commodities', 'symbol': 'CL=F', 'name': 'Crude Oil', 'tag': 'Energy', 'currency': 'USD'},
 {'watchlist_slug': 'commodities', 'symbol': 'HO=F', 'name': 'Heating Oil', 'tag': 'Energy', 'currency': 'USD'},
 {'watchlist_slug': 'commodities', 'symbol': 'NG=F', 'name': 'Natural Gas', 'tag': 'Energy', 'currency': 'USD'},
 {'watchlist_slug': 'commodities', 'symbol': 'RB=F', 'name': 'RBOB Gasoline', 'tag': 'Energy', 'currency': 'USD'},
 {'watchlist_slug': 'commodities', 'symbol': 'BZ=F', 'name': 'Brent Crude Oil', 'tag': 'Energy', 'currency': 'USD'},
 {'watchlist_slug': 'commodities', 'symbol': 'ZC=F', 'name': 'Corn', 'tag': 'Agriculture', 'currency': 'USX'},
 {'watchlist_slug': 'commodities', 'symbol': 'KE=F', 'name': 'Wheat', 'tag': 'Agriculture', 'currency': 'USX'},
 {'watchlist_slug': 'commodities', 'symbol': 'ZM=F', 'name': 'Soybean Meal', 'tag': 'Agriculture', 'currency': 'USD'},
 {'watchlist_slug': 'commodities', 'symbol': 'ZL=F', 'name': 'Soybean Oil', 'tag': 'Agriculture', 'currency': 'USX'},
 {'watchlist_slug': 'commodities', 'symbol': 'ZS=F', 'name': 'Soybean', 'tag': 'Agriculture', 'currency': 'USX'},
 {'watchlist_slug': 'commodities', 'symbol': 'GF=F', 'name': 'Feeder Cattle', 'tag': 'Livestock', 'currency': 'USX'},
 {'watchlist_slug': 'commodities', 'symbol': 'HE=F', 'name': 'Lean Hog', 'tag': 'Livestock', 'currency': 'USX'},
 {'watchlist_slug': 'commodities', 'symbol': 'LE=F', 'name': 'Live Cattle', 'tag': 'Livestock', 'currency': 'USX'},
 {'watchlist_slug': 'commodities', 'symbol': 'CC=F', 'name': 'Cocoa', 'tag': 'Agriculture', 'currency': 'USD'},
 {'watchlist_slug': 'commodities', 'symbol': 'KC=F', 'name': 'Coffee', 'tag': 'Agriculture', 'currency': 'USX'},
 {'watchlist_slug': 'commodities', 'symbol': 'CT=F', 'name': 'Cotton', 'tag': 'Agriculture', 'currency': 'USX'},
 {'watchlist_slug': 'commodities', 'symbol': 'SB=F', 'name': 'Sugar', 'tag': 'Agriculture', 'currency': 'USX'},
 {'watchlist_slug': 'commodities', 'symbol': 'SRUUF', 'name': 'Uranium', 'tag': 'Energy', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'NVDA', 'name': 'NVDA', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'AAPL', 'name': 'AAPL', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'GOOG', 'name': 'GOOG', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'MSFT', 'name': 'MSFT', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'AMZN', 'name': 'AMZN', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': '2330.TW', 'name': 'Taiwan Semi', 'tag': 'Global', 'currency': 'TWD'},
 {'watchlist_slug': 'global-99', 'symbol': 'META', 'name': 'META', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': '2222.SR', 'name': 'Saudi Aramco', 'tag': 'Global', 'currency': 'SAR'},
 {'watchlist_slug': 'global-99', 'symbol': 'TSLA', 'name': 'TSLA', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'AVGO', 'name': 'AVGO', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'BRK-A', 'name': 'Berkshire', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'WMT', 'name': 'WMT', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'LLY', 'name': 'LLY', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': '005930.KS', 'name': 'Samsung', 'tag': 'Global', 'currency': 'KRW'},
 {'watchlist_slug': 'global-99', 'symbol': 'JPM', 'name': 'JPM', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'XOM', 'name': 'XOM', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'V', 'name': 'V', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': '0700.HK', 'name': 'Tencent', 'tag': 'Global', 'currency': 'HKD'},
 {'watchlist_slug': 'global-99', 'symbol': 'JNJ', 'name': 'JNJ', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'ASML', 'name': 'ASML', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': '000660.KS', 'name': 'SK hynix', 'tag': 'Global', 'currency': 'KRW'},
 {'watchlist_slug': 'global-99', 'symbol': 'MU', 'name': 'MU', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'MA', 'name': 'MA', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'COST', 'name': 'COST', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'ORCL', 'name': 'ORCL', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'ABBV', 'name': 'ABBV', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'ROG.SW', 'name': 'Roche', 'tag': 'Global', 'currency': 'CHF'},
 {'watchlist_slug': 'global-99', 'symbol': 'PG', 'name': 'PG', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'BAC', 'name': 'BAC', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'HD', 'name': 'HD', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'CVX', 'name': 'CVX', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'GE', 'name': 'GE', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'NFLX', 'name': 'NFLX', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'CAT', 'name': 'CAT', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': '601398.SS', 'name': 'ICBC', 'tag': 'Global', 'currency': 'CNY'},
 {'watchlist_slug': 'global-99', 'symbol': 'KO', 'name': 'KO', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'AMD', 'name': 'AMD', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'PLTR', 'name': 'PLTR', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'MC.PA', 'name': 'LVMH', 'tag': 'Global', 'currency': 'EUR'},
 {'watchlist_slug': 'global-99', 'symbol': 'HSBA.L', 'name': 'HSBC', 'tag': 'Global', 'currency': 'GBp'},
 {'watchlist_slug': 'global-99', 'symbol': '601288.SS', 'name': 'Agri Bank China', 'tag': 'Global', 'currency': 'CNY'},
 {'watchlist_slug': 'global-99', 'symbol': 'AZN.L', 'name': 'AstraZeneca', 'tag': 'Global', 'currency': 'GBp'},
 {'watchlist_slug': 'global-99', 'symbol': 'NOVN.SW', 'name': 'Novartis', 'tag': 'Global', 'currency': 'CHF'},
 {'watchlist_slug': 'global-99', 'symbol': 'BABA', 'name': 'BABA', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': '7203.T', 'name': 'Toyota', 'tag': 'Global', 'currency': 'JPY'},
 {'watchlist_slug': 'global-99', 'symbol': 'CSCO', 'name': 'CSCO', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'LRCX', 'name': 'LRCX', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'AMAT', 'name': 'AMAT', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'MRK', 'name': 'MRK', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'PM', 'name': 'PM', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': '601857.SS', 'name': 'PetroChina', 'tag': 'Global', 'currency': 'CNY'},
 {'watchlist_slug': 'global-99', 'symbol': 'MS', 'name': 'MS', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'GS', 'name': 'GS', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99',
  'symbol': '0939.HK',
  'name': 'China Construction Bank',
  'tag': 'Global',
  'currency': 'HKD'},
 {'watchlist_slug': 'global-99', 'symbol': '600519.SS', 'name': 'Kweichow Moutai', 'tag': 'Global', 'currency': 'CNY'},
 {'watchlist_slug': 'global-99', 'symbol': 'NESN.SW', 'name': 'Nestle', 'tag': 'Global', 'currency': 'CHF'},
 {'watchlist_slug': 'global-99', 'symbol': 'WFC', 'name': 'WFC', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'RTX', 'name': 'RTX', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'UNH', 'name': 'UNH', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'RMS.PA', 'name': 'Hermes', 'tag': 'Global', 'currency': 'EUR'},
 {'watchlist_slug': 'global-99', 'symbol': 'OR.PA', 'name': "L'Oreal", 'tag': 'Global', 'currency': 'EUR'},
 {'watchlist_slug': 'global-99', 'symbol': '300750.SZ', 'name': 'CATL', 'tag': 'Global', 'currency': 'CNY'},
 {'watchlist_slug': 'global-99', 'symbol': 'RY.TO', 'name': 'Royal Bank of Canada', 'tag': 'Global', 'currency': 'CAD'},
 {'watchlist_slug': 'global-99', 'symbol': 'MCD', 'name': 'MCD', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'GEV', 'name': 'GEV', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'TMUS', 'name': 'TMUS', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'LIN', 'name': 'LIN', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'SHEL.L', 'name': 'Shell', 'tag': 'Global', 'currency': 'GBp'},
 {'watchlist_slug': 'global-99', 'symbol': 'AXP', 'name': 'AXP', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'PEP', 'name': 'PEP', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': '601988.SS', 'name': 'Bank of China', 'tag': 'Global', 'currency': 'CNY'},
 {'watchlist_slug': 'global-99', 'symbol': 'INTC', 'name': 'INTC', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'IBM', 'name': 'IBM', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'SIE.DE', 'name': 'Siemens', 'tag': 'Global', 'currency': 'EUR'},
 {'watchlist_slug': 'global-99', 'symbol': 'SAP.DE', 'name': 'SAP', 'tag': 'Global', 'currency': 'EUR'},
 {'watchlist_slug': 'global-99', 'symbol': '600941.SS', 'name': 'China Mobile', 'tag': 'Global', 'currency': 'CNY'},
 {'watchlist_slug': 'global-99', 'symbol': 'CBA.AX', 'name': 'Commonwealth Bank', 'tag': 'Global', 'currency': 'AUD'},
 {'watchlist_slug': 'global-99', 'symbol': 'ITX.MC', 'name': 'Inditex', 'tag': 'Global', 'currency': 'EUR'},
 {'watchlist_slug': 'global-99', 'symbol': 'RELIANCE.NS', 'name': 'Reliance', 'tag': 'Global', 'currency': 'INR'},
 {'watchlist_slug': 'global-99', 'symbol': 'VZ', 'name': 'VZ', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'AMGN', 'name': 'AMGN', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'BHP.AX', 'name': 'BHP', 'tag': 'Global', 'currency': 'AUD'},
 {'watchlist_slug': 'global-99', 'symbol': 'C', 'name': 'C', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': '8306.T', 'name': 'Mitsubishi UFJ', 'tag': 'Global', 'currency': 'JPY'},
 {'watchlist_slug': 'global-99', 'symbol': 'ABT', 'name': 'ABT', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'KLAC', 'name': 'KLAC', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'TMO', 'name': 'TMO', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'DTE.DE', 'name': 'Deutsche Telekom', 'tag': 'Global', 'currency': 'EUR'},
 {'watchlist_slug': 'global-99', 'symbol': 'SAN.MC', 'name': 'Banco Santander', 'tag': 'Global', 'currency': 'EUR'},
 {'watchlist_slug': 'global-99', 'symbol': 'TXN', 'name': 'TXN', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'T', 'name': 'T', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'NEE', 'name': 'NEE', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'DIS', 'name': 'DIS', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'CRM', 'name': 'CRM', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'APH', 'name': 'APH', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'BA', 'name': 'BA', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'ISRG', 'name': 'ISRG', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'GILD', 'name': 'GILD', 'tag': 'Global', 'currency': 'USD'},
 {'watchlist_slug': 'global-99', 'symbol': 'SCCO', 'name': 'SCCO', 'tag': 'Global', 'currency': 'USD'}]

SEED_TAG_COLORS = {'Cyclical': {'bg': 'rgba(252, 129, 129, .1)', 'text': '#fc8181', 'border': 'rgba(252, 129, 129, .3)'},
 'Defensive': {'bg': 'rgba(104, 211, 145, .1)', 'text': '#68d391', 'border': 'rgba(104, 211, 145, .3)'},
 'North America': {'bg': 'rgba(99, 179, 237, .1)', 'text': '#63b3ed', 'border': 'rgba(99, 179, 237, .3)'},
 'Europe': {'bg': 'rgba(246, 173, 85, .1)', 'text': '#f6ad55', 'border': 'rgba(246, 173, 85, .3)'},
 'Asia': {'bg': 'rgba(167, 139, 250, .1)', 'text': '#a78bfa', 'border': 'rgba(167, 139, 250, .3)'},
 'Latin America': {'bg': 'rgba(236, 72, 153, .1)', 'text': '#ec4899', 'border': 'rgba(236, 72, 153, .3)'},
 'Middle East': {'bg': 'rgba(251, 191, 36, .1)', 'text': '#fbbf24', 'border': 'rgba(251, 191, 36, .3)'},
 'Africa': {'bg': 'rgba(52, 211, 153, .1)', 'text': '#34d399', 'border': 'rgba(52, 211, 153, .3)'},
 'Oceania': {'bg': 'rgba(45, 212, 191, .1)', 'text': '#2dd4bf', 'border': 'rgba(45, 212, 191, .3)'},
 'Metals': {'bg': 'rgba(236, 201, 75, .1)', 'text': '#ecc94b', 'border': 'rgba(236, 201, 75, .3)'},
 'Energy': {'bg': 'rgba(237, 137, 54, .1)', 'text': '#ed8936', 'border': 'rgba(237, 137, 54, .3)'},
 'Carbon': {'bg': 'rgba(56, 178, 172, .1)', 'text': '#38b2ac', 'border': 'rgba(56, 178, 172, .3)'},
 'Agriculture': {'bg': 'rgba(154, 230, 180, .1)', 'text': '#9ae6b4', 'border': 'rgba(154, 230, 180, .3)'},
 'Livestock': {'bg': 'rgba(213, 63, 140, .1)', 'text': '#d53f8c', 'border': 'rgba(213, 63, 140, .3)'},
 'Other': {'bg': 'rgba(160, 174, 192, .1)', 'text': '#a0aec0', 'border': 'rgba(160, 174, 192, .3)'}}
